language: node_js
cache: yarn
node_js:
  - node
  - '14'
os:
  - linux
  - osx
branches:
  only:
    - master
    - '/^greenkeeper/.*$/'
script:
  - npm lint
  - npm test
after_success:
  - yarn coverage
jobs:
  include:
    - stage: release
      if: branch IN (master, next)
      node_js: node
      script:
        - npx semantic-release
      env:
        - secure: frJ1++In/b6TaMfj5KH69L4i5GEOQ1yYRTiFGI9uG2v/Fn55DT+sehPWIS+ADEozS3B/jjptH2OWrhlT4F2DIvxDuAQxeLM5Gpi8GLTLkreG3yOAMc20b2S3Ynco8b4CsLBikN91RYibINkUEV3TN54/BTJHQAOD0JPnh3EeA8W0HdGhBPv/k58bM8KlM4bkYVMXbhKEiynb67Uk/uattSlH3KlvWP7vgCY6Kn9uBTa47Dn5opL/JGaj/U1FpAo0yW6tMJ12kJ6NKFx8RYxd0CERIEcRWWcaZSmhocUzVO820/nhWrqFIZk3ADc9K0NGNyU24pQiyo2OFM+MHoiuD9p+TFIZPfjikKZqiwjad70XOstbhmDgO12TReseCTlH2/9Y+JNSujmAzg1SrdzA/SGo1NhV6ima84j0c3jiSmrYP/jNa6MzrstKMLs5irFckeInURI8nBDIiw42QNll8TBr8RVnE6Pzi4p2WccqEfiuOPS5Xls2E2h6xdXVAMZ3v06jAdTaTItP26hPPMgmVFU9PmMnL4aWPcQoWYkfpi1VD0NPRv2zTMC1hhF8SrJXMZE9/D7rL+fZ/JrUo3vYB1wzIqfe7fa7Qrz0ebboUOD5KhpBZAvEeGt99ptDAjp1y8BdiGRYlcjc7nhfBV9fBJrG1AU3fmyOjgzy7GhYNIM=
        - secure: J0aRMYmMw5ZzBKs3snK85U2PxyD6mO4XErNNApA5gZknQYv8WlLRtSxNSRMOEPlN16N2ylbK6O2A7Lytw9hV3pRM0YNTzi04/clPGNJxSi3TTKYuZXe8Jw/jOklc4RemUqWQQuDOEne3jOmizDnn0DetqcYBdJHw0ULLlbpFMYj+TBf4iROCd0a6HX2kvF5bypvf5JfZz9jyfkNlgZukMK6hWZFPdVtkAf6wS7wMKwu6TmYYGgiodFYdS9uF6BMsUgjdeHhhGUXBQKpXsmyMYZK/Pt/vffhI+6EguB/lOnPHQMRSsfR4iFAVK7q12P10kCvb9sg+oG3z1v8JN3k5kD6O4znrWu+NXCld+0EFnL+E4YjBstIleRrx1I14cgWtad9C9PWsfiNsx7ItyZ+JeHxtzQ9zDyhzA/+t2/eZbthU1QTA+mZY0yvp+VPyRfBvWPu+R966H9i9y4ycWqN7LvwQHgx4rwqvTQ8wYfgdlrWUtgZEDl2OoofAaKI0NwbGxt9pzQvrtN6yMVxPKC6ALdF8bUbUdfTFZkZgrVWC1CfliMWZ5MVBMhdNKru176/ZFzmTpzv+Oi+JGTbuc9Hps8vJkfFegiRSp28MjfPjSsHAagU4ElaCzg2xBbW1CJi8NASpH4OLqdl0J4Kp8EHhFipJwGeQdGsJeCkuVFxao78=
